urdfdom depend to be liburdfdom-dev on indigo
To fix (from a workspace containing joint_limits_interface):
rosdep install --from-paths src --ignore-src --rosdistro indigo -y

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
joint_limits_interface: Cannot locate rosdep definition for [urdfdom]

As said in:
http://wiki.ros.org/urdfdom
 "You should depend on liburdfdom-dev directly."